---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: $container_name
    network_mode: host #optional
    environment:
      - PUID=$PUID #optional
      - PGID=$PGID #optional
      - TZ=$TZ #optional
      - SUBDOMAINS=$SUBDOMAINS
      - TOKEN=$TOKEN
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - $CONFIG:/config #optional
    restart: unless-stopped
